### ISSUE TITLE
url is not defined

### ISSUE THREAD

**Issue by sai-tirunagiri** [QyrusAI/bitrise-step-qyrus-mobility-test-runner-android#1]
When trying to run the step, the step is failing for the following reason.

```
let host_name = url.parse(gatewayUrl).hostname;
                ^
ReferenceError: url is not defined
    at Object.<anonymous> (/tmp/bitrise982183872/step_src/upload.js:21:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
```

Thanks.

**Comment by QyrusAI** [comment]
This is fixed by adding the required nodejs library.
